const CATALOG = [
  { key: 'store.invoice_prefix', group: 'store', type: 'string', default: 'INV', scopes: ['tenant', 'branch', 'device'], legacy: { group: 'store_settings', field: 'invoice_prefix' } },
  { key: 'store.invoice_footer', group: 'store', type: 'string', default: 'Thank you for shopping with us.', scopes: ['tenant', 'branch', 'device'], legacy: { group: 'store_settings', field: 'invoice_footer' } },
  { key: 'store.currency', group: 'store', type: 'enum', default: 'INR', values: ['INR'], scopes: ['tenant', 'branch'], legacy: { group: 'store_settings', field: 'currency' } },
  { key: 'store.auto_sync', group: 'store', type: 'boolean', default: true, scopes: ['tenant', 'branch', 'device'], legacy: { group: 'store_settings', field: 'auto_sync' } },
  { key: 'store.notifications_enabled', group: 'store', type: 'boolean', default: true, scopes: ['tenant', 'branch', 'device'], legacy: { group: 'store_settings', field: 'notifications_enabled' } },
  { key: 'store.biometric_lock', group: 'store', type: 'boolean', default: false, scopes: ['tenant', 'branch', 'device'], legacy: { group: 'store_settings', field: 'biometric_lock' } },
  { key: 'tax.default_tax_percent', group: 'tax', type: 'number', default: 18, min: 0, max: 100, scopes: ['tenant', 'branch'], legacy: { group: 'tax_settings', field: 'default_tax_percent' } },
  { key: 'tax.gst_mode', group: 'tax', type: 'enum', default: 'INCLUSIVE', values: ['INCLUSIVE', 'EXCLUSIVE'], scopes: ['tenant', 'branch'] },
  { key: 'printer.receipt_paper_width_mm', group: 'receipt', type: 'enum_number', default: 80, values: [58, 80], scopes: ['tenant', 'branch', 'device'], legacy: { group: 'printer_settings', field: 'receipt_paper_width_mm' } },
  { key: 'receipt.auto_print', group: 'receipt', type: 'boolean', default: false, scopes: ['tenant', 'branch', 'device'] },
  { key: 'receipt.copies', group: 'receipt', type: 'integer', default: 1, min: 1, max: 5, scopes: ['tenant', 'branch', 'device'] },
  { key: 'theme.desktop', group: 'theme', type: 'enum', default: 'dark', values: ['dark', 'light'], scopes: ['tenant', 'device'], legacy: { group: 'theme_settings', field: 'desktop' } },
  { key: 'theme.mobile', group: 'theme', type: 'enum', default: 'dark', values: ['dark', 'light'], scopes: ['tenant', 'device'], legacy: { group: 'theme_settings', field: 'mobile' } },
  { key: 'billing.allow_negative_stock', group: 'billing', type: 'boolean', default: false, scopes: ['tenant', 'branch', 'device'] },
  { key: 'billing.allow_discount', group: 'billing', type: 'boolean', default: true, scopes: ['tenant', 'branch', 'device'] },
  { key: 'billing.max_discount_percent', group: 'billing', type: 'number', default: 20, min: 0, max: 100, scopes: ['tenant', 'branch', 'device'] },
  { key: 'billing.allow_price_override', group: 'billing', type: 'boolean', default: false, scopes: ['tenant', 'branch', 'device'] },
  { key: 'billing.customer_required', group: 'billing', type: 'boolean', default: false, scopes: ['tenant', 'branch', 'device'] },
  { key: 'billing.default_payment_method', group: 'billing', type: 'enum', default: 'cash', values: ['cash', 'upi', 'card', 'credit'], scopes: ['tenant', 'branch', 'device'] },
  { key: 'billing.enabled_payment_methods', group: 'billing', type: 'string_array', default: ['cash', 'upi', 'card'], scopes: ['tenant', 'branch', 'device'] },
  { key: 'billing.allow_split_payment', group: 'billing', type: 'boolean', default: true, scopes: ['tenant', 'branch', 'device'] },
  { key: 'billing.opening_required', group: 'billing', type: 'boolean', default: true, scopes: ['tenant', 'branch'] },
  { key: 'billing.closing_required', group: 'billing', type: 'boolean', default: true, scopes: ['tenant', 'branch'] },
  { key: 'inventory.piece_based_enabled', group: 'inventory', type: 'boolean', default: true, scopes: ['tenant', 'branch'] },
  { key: 'inventory.weight_based_enabled', group: 'inventory', type: 'boolean', default: true, scopes: ['tenant', 'branch'] },
  { key: 'inventory.weight_precision', group: 'inventory', type: 'integer', default: 3, min: 0, max: 6, scopes: ['tenant', 'branch', 'device'] },
  { key: 'inventory.batch_tracking_enabled', group: 'inventory', type: 'boolean', default: true, scopes: ['tenant', 'branch'] },
  { key: 'inventory.expiry_tracking_enabled', group: 'inventory', type: 'boolean', default: true, scopes: ['tenant', 'branch'] },
  { key: 'inventory.low_stock_alerts_enabled', group: 'inventory', type: 'boolean', default: true, scopes: ['tenant', 'branch'] },
  { key: 'offline.sales_enabled', group: 'offline', type: 'boolean', default: true, scopes: ['tenant', 'branch', 'device'] },
  { key: 'offline.max_offline_hours', group: 'offline', type: 'integer', default: 72, min: 1, max: 720, scopes: ['tenant', 'branch', 'device'] },
  { key: 'offline.sync_interval_seconds', group: 'offline', type: 'integer', default: 60, min: 5, max: 3600, scopes: ['tenant', 'branch', 'device'] },
  { key: 'offline.require_recent_config_hours', group: 'offline', type: 'integer', default: 168, min: 1, max: 2160, scopes: ['tenant', 'branch', 'device'] },
  { key: 'security.manager_approval_void', group: 'security', type: 'boolean', default: true, scopes: ['tenant', 'branch', 'device'] },
  { key: 'security.manager_approval_refund', group: 'security', type: 'boolean', default: true, scopes: ['tenant', 'branch', 'device'] },
  { key: 'security.session_timeout_minutes', group: 'security', type: 'integer', default: 480, min: 5, max: 1440, scopes: ['tenant', 'branch', 'device'] },
  { key: 'hardware.barcode_scanner_enabled', group: 'hardware', type: 'boolean', default: true, scopes: ['tenant', 'branch', 'device'] },
  { key: 'hardware.weighing_scale_enabled', group: 'hardware', type: 'boolean', default: false, scopes: ['tenant', 'branch', 'device'] },
  { key: 'hardware.cash_drawer_enabled', group: 'hardware', type: 'boolean', default: false, scopes: ['tenant', 'branch', 'device'] },
];

const CATALOG_BY_KEY = new Map(CATALOG.map((entry) => [entry.key, entry]));

const publicCatalog = () => CATALOG.map((entry) => ({
  key: entry.key,
  group: entry.group,
  type: entry.type,
  default: entry.default,
  values: entry.values || null,
  min: entry.min ?? null,
  max: entry.max ?? null,
  scopes: entry.scopes,
  legacy_backed: Boolean(entry.legacy || entry.key === 'tax.gst_mode'),
}));

module.exports = { CATALOG, CATALOG_BY_KEY, publicCatalog };
